### PR TITLE
Capitalized, clean up

### PR DESCRIPTION
**Pull request by RichardLitt**

### CODE REVIEW

**Comment by whyrusleeping** [comment]
@RichardLitt you broke my tests!

**Comment by RichardLitt** [comment]
...hooray? I'm guessing you want me to fix those, too?

**Comment by whyrusleeping** [comment]
probably, yeah. Its just adjusting the expected message in the test thats failing

**Comment by hsanjuan** [comment]
Tests were having other problems too (see https://github.com/ipfs/ipfs-update/pull/34)

**Comment by RichardLitt** [comment]
I removed all uppercase and final periods for `.Fatal` and `.Error`. That should be in accordance with go standards.

**Comment by whyrusleeping** [comment]
@RichardLitt could you rebase this on master?

**Comment by RichardLitt** [comment]
@whyrusleeping Done.

**Comment by whyrusleeping** [comment]
@RichardLitt youre gonna have to update the tests since you changed the output theyre checking against.

**Comment by RichardLitt** [comment]
@whyrusleeping  Passed!

**Pull request merged**
